// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpehetoiyerwleqkxng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cGVoZXRvaXllcndsZXFreG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzc1OTIsImV4cCI6MjA2NDcxMzU5Mn0.AzMDj9g8GEaBdT8NJ0gKtnT8O9xyEW7SAU1HtMrFeTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);